services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: UTC
      PGTIMEZONE: UTC
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"